server:
  port: 80  servlet:    context-path: /
  #数据源
spring:  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wyx?serverTimezone=UTC
    username: root
    password: root  jpa:    database: mysql    show-sql: true
    hibernate:      ddl-auto: update    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  freemarker:    suffix: .ftl